\connect ups_system_db

-- ========================================
-- Sequences
-- ========================================
ALTER TABLE public.retail_centers
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.retail_centers_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );

ALTER TABLE public.shipped_items
    ALTER COLUMN item_num ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.shipped_items_item_num_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );

ALTER TABLE public.transportation_events
    ALTER COLUMN seq_number ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.transportation_event_seq_number_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );

SELECT pg_catalog.setval('public.retail_centers_id_seq', 1, false);
SELECT pg_catalog.setval('public.shipped_items_item_num_seq', 1, false);
SELECT pg_catalog.setval('public.transportation_event_seq_number_seq', 1, false);
-- ========================================

-- ========================================
-- Primary keys
-- ========================================
-- -- Remove duplicates to create primary key in "item_transportations"
-- WITH duplicates AS (SELECT ctid,
--                            ROW_NUMBER() OVER (
--                                PARTITION BY transportation_event_seq_number, shipped_item_item_num
--                                ORDER BY ctid
--                                ) AS rn
--                     FROM public.item_transportations)
-- DELETE
-- FROM public.item_transportations
-- WHERE ctid IN (SELECT ctid
--                FROM duplicates
--                WHERE rn > 1);

ALTER TABLE ONLY public.item_transportations
    ADD CONSTRAINT item_transportations_pkey PRIMARY KEY (transportation_event_seq_number, shipped_item_item_num);

ALTER TABLE ONLY public.retail_centers
    ADD CONSTRAINT retail_centers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.shipped_items
    ADD CONSTRAINT shipped_items_pkey PRIMARY KEY (item_num);

ALTER TABLE ONLY public.transportation_events
    ADD CONSTRAINT transportation_event_pkey PRIMARY KEY (seq_number);
-- ========================================

-- ========================================
-- Foreign keys
-- ========================================
ALTER TABLE ONLY public.shipped_items
    ADD CONSTRAINT fk_retail_center_id FOREIGN KEY (retail_center_id) REFERENCES public.retail_centers (id) ON DELETE CASCADE;

ALTER TABLE ONLY public.item_transportations
    ADD CONSTRAINT fk_shipped_item_item_num FOREIGN KEY (shipped_item_item_num) REFERENCES public.shipped_items (item_num) ON DELETE CASCADE;

ALTER TABLE ONLY public.item_transportations
    ADD CONSTRAINT fk_transportation_event_seq_number FOREIGN KEY (transportation_event_seq_number) REFERENCES public.transportation_events (seq_number) ON DELETE CASCADE;
-- ========================================